blank_issues_enabled: true
contact_links:
  - name: Ideas, questions and help requests
    url:  https://github.com/fiskaltrust/middleware/discussions
    about: Please ask questions and discuss ideas in our discussion section
