name: Check linked issue

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-linked-issues:
    runs-on: ubuntu-latest
    name: Issue needs to be linked
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check linked issues
        uses: ./.github/actions/check-linked-issue
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repository: ${{ github.repository }}
          skip: ${{ contains(github.event.pull_request.labels.*.name, 'meta-no-issue') }}
          github-token: ${{ secrets.READ_ISSUES_TOKEN }}
